p.csv issue update
nrel-hem/HolisticElectricityModel.jl pull request #26
Opened 2024-11-21 23:10 UTC by bcakire

2024-11-26 14:10 UTC, elainethale requested changes

2024-11-26 14:10 UTC, elainethale commented on src/agents/common.jl
> +    end
We shouldn't need project-specific code in common.jl.

2024-11-26 14:10 UTC, elainethale commented on src/agents/common.jl
> +        county_to_ba,
Again, "county" is too project-specific. Perhaps what's needed is for an "index_h_z_mapping.csv" to be made in HEMData.jl similar to "index_h_sector_mapping.csv"?

2025-05-15 22:29 UTC, elainethale requested changes
Mostly questions and comments. I would like to see a comparison of ParamArray values accessed by key versus reading the same data in as a DataFrame and filtering.

2025-05-15 22:29 UTC, elainethale commented on src/agents/common.jl
> +    # the input directory.
Created issue https://github.com/nrel-hem/HolisticElectricityModelData.jl/issues/28 to provide the needed data and issue https://github.com/nrel-hem/HolisticElectricityModel.jl/issues/50 to use the data when they are available.

2025-05-15 22:29 UTC, elainethale commented on src/types.jl
> +# TODO: Validate vals against dims
Relates to #7

2025-05-15 22:29 UTC, elainethale commented on src/agents/regulator.jl
> +            # Behind-the-meter generation for PV-only customers
Similar text was deleted above. Was that on purpose? (Is this text more relevant here than above where it was deleted?)

2025-05-15 22:29 UTC, elainethale commented on src/agents/regulator.jl
> +                # Behind-the-meter generation for PV+Storage customers not participating in aggregation
Another place where text that was kept and reformatted above was deleted.

2025-05-15 22:29 UTC, elainethale commented on src/agents/customer_group.jl
> +        map_dict = Dict(index_h_to_sector_map.set)
```suggestion
        map_dict = Dict(index_h_to_sector_map)
```

based on line 1565 in regulator.jl, e.g., where it says:
```julia
        # Assign rates to customers
        h_to_sector = Dict(model_data.index_h_sector_map)
```

2025-05-15 22:29 UTC, elainethale commented on src/agents/regulator.jl
> +        # Replace NaN values with 0.0
Is this still needed? Would it be an error that we want to know about if p.values ends up with any NaNs?

2025-05-15 22:29 UTC, elainethale commented on src/agents/regulator.jl
> +            # Since this net demand is for rate calculation, we need to consider energy offset at the household level.
Either keep the whole comment or delete the whole comment. I don't feel strongly either way. I think it's largely a reminder to think about whether each h category should be split into those with DER and those without DER when processing here.

2025-05-15 22:29 UTC, elainethale commented on src/agents/utility.jl
> +    @show z_to_h_dict
```suggestion
    z_to_h_dict = get_one_to_many_dict(model_data.index_z_h_map, :index_z)
```

Sorry--I think I left this debugging code in when I passed the branch back last time.

2025-05-15 22:29 UTC, elainethale commented on test/test_utils.jl
> +@testset "test read_param with county level index" begin
Could use some more spacing? E.g., on either side of the line defining `test_dir`?

2025-05-15 22:29 UTC, elainethale commented on test/test_utils.jl
> +        @test !(ismissing(valid_param(h, m, z, d, t)))
Let's also read in the file as a DataFrame and verify that the values are the same when we search by index.

2025-05-23 01:56 UTC, purboday commented on src/agents/regulator.jl
> +        # Replace NaN values with 0.0
Removed the NaN filling and replaced it with throwing an error.

2025-05-23 01:56 UTC, purboday commented on src/agents/customer_group.jl
> +
Removing this.

2025-05-23 02:12 UTC, purboday commented on src/agents/regulator.jl
> +            # Since this net demand is for rate calculation, we need to consider energy offset at the household level.
Reverted.

2025-05-23 02:12 UTC, purboday commented on test/test_utils.jl
> +        @test !(ismissing(valid_param(h, m, z, d, t)))
Added a test case.

2025-05-23 02:20 UTC, purboday commented
@elainethale Tested this with both BA and county level inputs and also ran the comparison test with `main` to ensure there were no more significant differences in the results.

2025-05-23 17:15 UTC, elainethale approved these changes
I ran a case and results were exactly the same!

2025-05-23 17:15 UTC, elainethale commented on src/agents/der_aggregator.jl
> +        duration_dist_stor = first(x for x in customers.duration_dist_stor(z,:) if x != 0)
Just curious--was this the cause of the mismatches?

2025-05-23 17:35 UTC, purboday commented on src/agents/der_aggregator.jl
> +        duration_dist_stor = first(x for x in customers.duration_dist_stor(z,:) if x != 0)
Yes, `findfirst` actually returns the index and not the value, so these were being set incorrectly.

2025-05-23 18:49 UTC, merged